config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :corrections, only: [:create, :destroy]
  devise_for :users

  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  has_many :corrections
end

app/models/correction.rb
class Correction < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user

  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers
  has_many :corrections
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create
		@answer = current_user.answers.build(answer_params)
		@answer.save

		redirect_to @answer.question
	end

	private
    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:content, :user_id, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/corrections_controller.rb
class CorrectionsController < ApplicationController
	def create
		@correction = current_user.corrections.build(correction_params)
		@correction.save

		redirect_to @correction.answer.question
	end

	private
    # Never trust parameters from the scary internet, only allow the white list through.
    def correction_params
      params.require(:correction).permit(:content, :user_id, :answer_id)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = Answer.new
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corrections_helper.rb
module CorrectionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cafe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Cafe", root_path, class: "navbar-brand" %> 
    </div>
    <ul class="nav navbar-nav navbar-right">
    	<li>
    		<% if user_signed_in? %>
    			<%= link_to "로그아웃", destroy_user_session_path, method: :delete %>
    		<% else %>
	    		<%= link_to "로그인", new_user_session_path  %>
	    	<% end %>
    	</li>
    </ul>
  </div>
</nav>
<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<% @questions.each do |question| %>
  <div class="well">
    <%= link_to question.content, question %>
  </div>
<% end %>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<h3><%= @question.content %></h3>
<p><%= @question.user.email %></p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

<%= simple_form_for(@answer) do |f| %>
	<%= f.input :content, label: "Answer" %>
	<%= f.hidden_field :question_id, value: @question.id %>
	<%= f.submit "답 등록하기", class: "btn btn-default" %>
<% end %>

<hr>

<% @question.answers.each do |answer| %>
	<div class="well">
    <%= answer.content %> by <%= answer.user.email %>

    <div>
    	<% answer.corrections.each do |correction| %>
    		<div class="alert alert-info" role="alert">
    			- <%= correction.content %> by <%= correction.user.email %>
    		</div>
    	<% end %>
	    <%= simple_form_for(Correction.new) do |f| %>
				<%= f.input :content, label: "Correction" %>
				<%= f.hidden_field :answer_id, value: answer.id %>
				<%= f.submit "수정 등록하기", class: "btn btn-default" %>
			<% end %>
		</div>
  </div>
<% end %>